<a href="https://colab.research.google.com/github/malakhovs04/ml_labs/blob/main/laba_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from sklearn.decomposition import PCA
from numpy import corrcoef

1. Загрузите выборку

In [3]:
data = pd.read_csv('/content/close_prices.csv')
data

,date,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
0,2013-09-23,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
1,2013-09-24,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2,2013-09-25,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
3,2013-09-26,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
4,2013-09-27,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,2015-03-12,81.559998,152.039993,80.190002,28.240000,102.419998,80.400001,107.169998,25.400000,189.949997,...,34.000000,82.089996,33.130001,107.830002,114.879997,121.239998,269.579987,48.730000,81.900002,84.220001
370,2015-03-13,80.599998,151.570007,79.230003,27.940001,101.620003,80.499997,106.440002,25.040001,189.339996,...,34.000000,81.830002,32.759998,106.720001,115.250000,118.739998,265.029999,48.840000,81.900002,83.870003
371,2015-03-16,81.500000,153.669998,79.970001,28.299999,103.129997,77.069994,107.370003,25.450001,191.899994,...,34.439999,83.559998,33.060001,108.930000,118.519997,120.070000,269.019989,49.270000,83.290001,84.760002
372,2015-03-17,81.059998,154.509995,78.449997,28.150000,103.169998,74.680001,106.959999,25.309999,190.570007,...,34.169998,82.849998,32.900002,108.750000,117.599998,119.860001,264.500000,48.950001,82.620003,84.080002
373,2015-03-18,81.860001,155.729996,81.330002,28.150000,106.699997,76.009997,107.970001,25.639999,192.320007,...,34.380001,83.750000,33.590000,109.519997,119.959999,120.309998,267.670013,49.540001,82.529999,86.070000

2. Обучите преобразование PCA

In [6]:
pca = PCA(n_components=10)
result = pca.fit(data.iloc[:,1:31])
variance_ratio = result.explained_variance_ratio_
components = result.components_

In [7]:
componentsCount = 1
while sum(variance_ratio[:componentsCount])<0.9:
  componentsCount += 1

componentsCount

4

3. Примите к исходным преобразованиям

In [12]:
result = pca.transform(data.iloc[:,1:31])
firstComponent = result[:,0]
result

array([[-50.90240358, -17.63167724,  -7.7360209 , ...,   3.55657041,
          5.82197358,   1.72604005],
       [-52.84690919, -19.14690749,  -7.27254551, ...,   3.43259929,
          5.63318106,   2.0122316 ],
       [-54.61443917, -19.92735811,  -8.10995831, ...,   4.17520282,
          5.38828678,   2.75269933],
       ...,
       [ 83.79819948, -16.95241334,   8.25265611, ...,   2.92390381,
          4.59543822,   2.99033503],
       [ 79.19578947, -19.14436008,   6.93262976, ...,   3.40475421,
          3.66793327,   3.57607629],
       [ 82.96885933, -13.13513974,   9.07644299, ...,   3.75100423,
          4.79172198,   3.03918865]])

4. Загрузите информацию об идексе Доу-Джонса. Чему равна корреляция

In [13]:
data2 = pd.read_csv('/content/djia_index.csv')
data2

           date          ^DJI
0    2013-09-23  15401.379883
1    2013-09-24  15334.589844
2    2013-09-25  15273.259766
3    2013-09-26  15328.299805
4    2013-09-27  15258.240234
..          ...           ...
369  2015-03-12  17895.220703
370  2015-03-13  17749.310547
371  2015-03-16  17977.419922
372  2015-03-17  17849.080078
373  2015-03-18  18076.189453

[374 rows x 2 columns]

In [20]:
y=data2.iloc[:,1]
pearsonCoeffs=corrcoef(firstComponent, y)
print(round(pearsonCoeff[0,1],2))

0.91

5. Какая компания имеет наибольший вес в первой компоненте

In [21]:
firstComponent = pd.DataFrame(data = components[0])
index = firstComponent.idxmax()[0]+1
data.columns[index]

'V'